### PR TITLE
Drop Ruby < 2.3 support

### PR DESCRIPTION
**Pull request by pirj**
Better viewed ignoring indentation changes https://github.com/rspec/rspec-support/pull/436/files?diff=split&w=1

As per https://github.com/rspec/rspec/issues/61#issuecomment-687290045

Sibling PRs:
 - https://github.com/rspec/rspec-mocks/pull/1349
 - https://github.com/rspec/rspec-expectations/pull/1231
 - https://github.com/rspec/rspec-core/pull/2787

Minimal changes to `rspec-core` and `rspec-mocks` were required to run `rspec-support`'s own spec suite, pushed to branches with the same name.

## What has been done

Done:
- [x] clean up RubyFeatures
- [x] check respond_to?
- [x] check method_defined?
- [x] check send (where we call private methods that later became public)
- [x] cleanup Gemfile
- [x] update required_ruby_version
- [x] update VERSION
- [x] check RUBY_VERSION usages
- [x] check if we require_rspec_support ruby_features where RubyFeatures are not used
- [-] check define_method where def would suffice
- [x] check `(class << self; self; end)` usages for possibility to use `singleton_class` (some can't be replaced as `singleton_class` does create a singleton class if it doesn't exist yet)
- [x] check if Java::JavaLang::String.instance_method(:char_at).arity == -1
- [?] check Java::JavaLang::String.instance_method(:char_at).parameters == [] - still the case
- [x] check 1.8, 1.9, 2.0, 2.1, jruby, 9.0, 9.1, mri
- [x] check requires for support's mutex
- [x] check `eval`
- [x] check "work around", "workaround" - there are two cases: check if this was fixed in JRuby 9.2
- [x] check docs
- [-] ~WithKeywordsWhenNeeded~ - will be addressed separately
- [x] `gsub`/`unindent` where squiggly heredoc can be used
- [-] ~remove `ripper_supported?`~ - it has poor support in JRuby 9.1

### CODE REVIEW

**Comment by pirj** [comment]
For some reason, builds stopped triggering.
Going to switch to "ready for review" temporarily just to figure out if it's the case (quite unlikely though).

**Comment by benoittgt** [comment]
For the build issue it is because travisci config.  https://github.com/rspec/rspec-support/pull/436/commits/112973040cbab3bfb69b23bc21b03bc084c93e00

File: .rubocop_rspec_base.yml [hunk 1]
```diff
@@ -39,28 +39,12 @@ CyclomaticComplexity:
 Documentation:
   Enabled: false
 
-# We still support 1.8.7 which requires trailing dots
-DotPosition:
-  EnforcedStyle: trailing
```
Comment (JonRowe) [inline .rubocop_rspec_base.yml:44]: We should leave this rule to avoid churn

**Review by JonRowe — COMMENTED** [review]
Theres a whole bunch of unnecessary changes, I don't feel we need to switch to 1.9 style keys just because we can, similarly with the trailing dot changes.

I also think we should keep the mutex method binding, the reasoning behind it is sound, we just don't need the vendored implementation.

**Comment by pirj** [comment]
@JonRowe Thanks for the review.

I've outlined the things to discuss in the description, including:
> [?] extract rubocop changes into a separate pull request

I'll extract this into a separate follow-up pull request to `4-0-dev`.

File: lib/rspec/support/reentrant_mutex.rb [hunk 2]
```diff
@@ -40,22 +36,5 @@ def exit
         @mutex.unlock
       end
     end
-
-    if defined? ::Mutex
-      # On 1.9 and up, this is in core, so we just use the real one
-      class Mutex < ::Mutex
-        # If you mock Mutex.new you break our usage of Mutex, so
-        # instead we capture the original method to return Mutexs.
-        NEW_MUTEX_METHOD = Mutex.method(:new)
```
[the remark this answers is not in the document]
Comment (pirj) [reply lib/rspec/support/reentrant_mutex.rb:49]: Fair enough. Reminds me of the recent case with stubbed `File.read` 👍

File: lib/rspec/support/spec/shell_out.rb [hunk 3]
```diff
@@ -62,13 +45,6 @@ def run_ruby_with_current_load_path(ruby_command, *flags)
           %r{jruby-\d\.\d\.\d\.\d/lib/ruby/stdlib/rubygems},
           # This is required for windows for some reason
           %r{lib/bundler/rubygems},
-          # This is a JRuby file that generates warnings on 9.0.3.0
-          %r{lib/ruby/stdlib/jar},
-          # This is a JRuby file that generates warnings on 9.1.7.0
-          %r{org/jruby/RubyKernel\.java},
-          # This is a JRuby gem that generates warnings on 9.1.7.0
```
[the remark this answers is not in the document]
Comment (pirj) [reply lib/rspec/support/spec/shell_out.rb:69]: I remember @headius mentioned that for the end-users there is no good excuse for not using the latest 9.2 instead of any other JRuby version. Did I understand/remember this correctly?

File: lib/rspec/support/method_signature_verifier.rb [hunk 4]
```diff
@@ -177,37 +144,6 @@ def classify_parameters
...
-      # out matching methods (which could be more than one partly because Java
-      # supports multiple overloads, and partly because JRuby introduces
-      # aliases to make method names look more Rubyesque). If there is only a
-      # single match, we can use that methods arity directly instead of the
-      # default -1 arity.
-      #
-      # This workaround only works for Java proxy methods, and in order to
-      # support regular methods and blocks, we need to be careful about calling
-      # owner and java_class as they might not be available
-      if Java::JavaLang::String.instance_method(:char_at).arity == -1
```
[the remark this answers is not in the document]
Comment (pirj) [reply lib/rspec/support/method_signature_verifier.rb:192]: This is fixed in jruby-9.2.13.0, I'll double-check with earlier 9.2 versions.

File: lib/rspec/support/ruby_features.rb [hunk 5]
```diff
@@ -28,22 +27,10 @@ def jruby?
...
-      end
-
       def rbx?
         defined?(RUBY_ENGINE) && RUBY_ENGINE == 'rbx'
       end
 
-      def non_mri?
-        !mri?
-      end
-
```
[the remark this answers is not in the document]
Comment (pirj) [reply lib/rspec/support/ruby_features.rb:46]: I'm not sure if you specifically mean `non_mri?`? Couldn't find `non_mri` in git history in Mocks/Expectations/Core/Support.

File: lib/rspec/support/with_keywords_when_needed.rb [hunk 6]
```diff
@@ -8,26 +8,19 @@ module WithKeywordsWhenNeeded
...
-            CODE
-          else
-            klass.class_exec(*args, &block)
-          end
-        end
-        ruby2_keywords :class_exec if respond_to?(:ruby2_keywords, true)
-      else
-        def class_exec(klass, *args, &block)
+      # Remove this in RSpec 4 in favour of explictly passed in kwargs where
+      # this is used. Works around a warning in Ruby 2.7
```
[the remark this answers is not in the document]
Comment (pirj) [reply lib/rspec/support/with_keywords_when_needed.rb:12]: Sure, it's in TODO in the description:

> [ ] WithKeywordsWhenNeeded

File: rspec-support.gemspec [hunk 7]
```diff
@@ -33,8 +33,8 @@ Gem::Specification.new do |spec|
     spec.cert_chain = [File.expand_path('~/.gem/rspec-gem-public_cert.pem')]
   end
 
-  spec.required_ruby_version = '>= 1.8.7'
+  spec.required_ruby_version = '>= 2.3.0'
 
-  spec.add_development_dependency "rake",         "> 10.0.0"
+  spec.add_development_dependency "rake", ">= 12.3.3"
```
[the remark this answers is not in the document]
Comment (pirj) [reply rspec-support.gemspec:38]: I preferred to avoid updating libraries versions, [`12.3.3` comes from the `Gemfile`](https://github.com/rspec/rspec-support/blob/main/Gemfile#L21):
```ruby
gem 'rake', '>= 12.3.3'
```

File: script/functions.sh [hunk 8]
```diff
@@ -12,10 +12,8 @@ SPECS_HAVE_RUN_FILE=specs.out
 MAINTENANCE_BRANCH=`cat maintenance-branch`
 
 # Don't allow rubygems to pollute what's loaded. Also, things boot faster
-# without the extra load time of rubygems. Only works on MRI Ruby 1.9+
-if is_mri_192_plus; then
-  export RUBYOPT="--disable=gem"
-fi
+# without the extra load time of rubygems.
+export RUBYOPT="--disable=gem"
```
[the remark this answers is not in the document]
Comment (pirj) [reply script/functions.sh:16]: Sure, that's part of the iterative plan.

> for rspec-dev:
>   remove unused predicate_functions

I'm experimenting here to figure out what can be stripped off, so we can find what needs to remain because it's still used in some of the repos and what can be removed in `rspec-dev`. I'll extract this and will send a follow-up PR to `rspec-dev` and to other repos against `4-0-dev`.

File: spec/rspec/support/mutex_spec.rb [hunk 9]
```diff
@@ -1,8 +0,0 @@
-require 'rspec/support/mutex'
-
-RSpec.describe RSpec::Support::Mutex do
-  it "allows ::Mutex to be mocked", :if => defined?(::Mutex) do
-    expect(Mutex).to receive(:new)
-    ::Mutex.new
-  end
-end
```
[the remark this answers is not in the document]
Comment (pirj) [reply spec/rspec/support/mutex_spec.rb:8]: Ooops!

**Comment by pirj** [comment]
@JonRowe @benoittgt Appreciate if you can take a look at Discuss section of the description, there are some important questions, let me cite below:

1. introduce https://github.com/ruby/ruby2_keywords dependency and remove respond_to?(:ruby2_keywords, true) check
2. cleanup of build functions/predicates - any objections? (for sure in a separately pull request, and coming from rspec-dev)
3. drop Ruby 2.3 - problematic'ish due to a dependency on outdated OpenSSL, EOL'ed, not supported by RuboCop, still used by 8% of users
4. tweak clone_repo to accept a branch, use maintenance-branch's branch for main repos, and 4-0-maintenance for cloning rspec-rails since it's alienated anyway?

**Comment by JonRowe** [comment]
> [?] introduce https://github.com/ruby/ruby2_keywords dependency and remove respond_to?(:ruby2_keywords, true) check

No, we can't introduce dependencies.

> [?] drop Ruby 2.3 - problematic'ish due to a dependency on outdated OpenSSL, EOL'ed, not supported by RuboCop, still used by 8% of users

What Rubocop supports does not drive us. 2.3 is not really problematic.

> [?] tweak clone_repo to accept a branch, use maintenance-branch's branch for main repos, and 4-0-maintenance for cloning rspec-rails since it's alienated anyway?

It already does this? Its just hardcoded based on the branch?

> [?] extract rubocop changes into a separate pull request

Just remove them, they're unneeded.

**Comment by pirj** [comment]
> >    and 4-0-maintenance for cloning rspec-rails since it's alienated anyway?

> It already does this? Its just hardcoded based on the branch?

Doesn't seem to. The build was failing without `drop-old-rubies` `rspec-rails` branch. Also, it failed with default `version.rb`:

```
Resolving dependencies...

Bundler could not find compatible versions for gem "rspec-core":

  In Gemfile:
    rspec-core
    rspec-rails was resolved to 4.1.0.pre, which depends on
      rspec-core (= 3.11.0.pre)
```

Changed it to `4.0.0.pre` to trick this build.

**Comment by pirj** [comment]
I'm getting stuck with removing `WithKeywordsWhenNeeded` and dealing with kwargs delegation related failures.
Removal of `WithKeywordsWhenNeeded` is tangential to the removal of rubies, and I'm going to remove all `eval` hacks, but not kwargs delegation hacks.
I intend to address the removal of `WithKeywordsWhenNeeded` and kwargs delegation issues and hacks in a separate series of pull requests.

File: .github/workflows/ci.yml [hunk 10]
```diff
@@ -26,9 +26,11 @@ jobs:
           - 2.5
           - 2.4
           - 2.3
+          - jruby-9.2
```
Comment (pirj) [inline .github/workflows/ci.yml:29]: This worked fine https://github.com/rspec/rspec-support/pull/436/checks?check_run_id=1418962579

Are you interested in incorporating this in your GHA initiative?

I've removed `JRUBY_OPTS='--dev'` with no replacement for GHA. Not sure if it's needed.

The reason I'm doing this in this PR (temporarily) is to test this out while Travis is 🐌 
```
      # To work around JRuby error:
      # can't convert RSpec::Support::StdErrSplitter into String
```

Comment (pirj) [reply .github/workflows/ci.yml:29]: Sorry, forgot to mention @JonRowe ☝️

Comment (pirj) [reply .github/workflows/ci.yml:29]: `jruby-head` failure seems to be due:

```
Warning: the --server flag is deprecated and has no effect most JVMs
```

[This will be fixed in 9.3.0.0](https://github.com/jruby/jruby/issues/6147)

Wondering why it doesn't affect our `jruby-9.2` 😕

Comment (pirj) [reply .github/workflows/ci.yml:29]: And https://github.com/rspec/rspec-support/commit/33e6318 didn't help, since it outputs to stdout 😞

**Comment by pirj** [comment]
@JonRowe I intend to add back a `jruby-9.1` build job, and make an attempt to remove `ripper_supported?` after that.

File: lib/rspec/support/reentrant_mutex.rb [hunk 11]
```diff
@@ -40,22 +38,5 @@ def exit
...
```
Comment (JonRowe) [inline lib/rspec/support/reentrant_mutex.rb:49]: Just restore this and remove the other file, we don't need the file just this.

File: lib/rspec/support/spec/stderr_splitter.rb [hunk 12]
```diff
@@ -28,30 +26,12 @@ def reopen(*args)
...
-        return if line =~ %r{^\S+/gems/\S+:\d+: warning:} # http://rubular.com/r/kqeUIZOfPG
-
-        # Ruby 2.7.0 warnings from keyword argments span multiple lines, extend check above
-        # to look for the next line.
-        return if @last_line =~ %r{^\S+/gems/\S+:\d+: warning:} &&
-                  line =~ %r{warning: The called method .* is defined here}
-
-        # Ruby 2.7.0 complains about hashes used in place of keyword arguments
-        # Aruba 0.14.2 uses this internally triggering that here
-        return if line =~ %r{lib/ruby/2\.7\.0/fileutils\.rb:622: warning:}
```
Comment (JonRowe) [inline lib/rspec/support/spec/stderr_splitter.rb:49]: Restore these, we support all versions of 2.7.

File: lib/rspec/support/spec/stderr_splitter.rb [hunk 13]
```diff
@@ -28,30 +26,12 @@ def reopen(*args)
...
+        # Ignore warnings coming from gems, specifically Rails on Ruby 2.5+
+        return if line =~ %r{^\S+/gems/\S+:\d+: warning:}
```
Comment (JonRowe) [inline lib/rspec/support/spec/stderr_splitter.rb:31]: Don't change this logic when its unrelated, we don't want to become less specific.

File: .travis.yml [hunk 14]
```diff
@@ -15,27 +15,14 @@ before_install:
...
-  - JRUBY_OPTS='--dev'
 matrix:
   include:
-    - rvm: jruby-1.7
-      env: JRUBY_OPTS='--dev --1.8'
-    - rvm: 2.7.1
+    - rvm: 2.7.2
       env: DIFF_LCS_VERSION="~> 1.3.0"
-    - rvm: 2.7.1
+    - rvm: 2.7.2
```
Comment (JonRowe) [inline .travis.yml:23]: Don't need to bother changing these, they will be on github actions soon enough.

File: .travis.yml [hunk 15]
```diff
@@ -15,27 +15,14 @@ before_install:
 bundler_args: "--binstubs --standalone --without documentation --path ../bundle"
 script: "script/run_build"
 rvm:
-  - 1.8.7
```
Comment (JonRowe) [inline .travis.yml:18]: Really you can just delete this file, we won't be using travis for RSpec 4's CI.

File: .github/workflows/ci.yml (hunk 10 above)
Comment (JonRowe) [reply .github/workflows/ci.yml:29]: I'd leave this the same as main but remove the 2 old rubies.

File: .travis.yml (hunk 15 above)
Comment (pirj) [reply .travis.yml:18]: That's for sure, once it's all done.
But before it was done, I preferred to have at least some builds to constantly updating two repos I was actively committing to to `drop-old-rubies` to those frequent commits to `4-0-dev`.
Once it's all settled, I'll go through all the changes thoroughly again myself and will ask for a detailed review.

File: lib/rspec/support/spec/shell_out.rb [hunk 16]
```diff
@@ -16,26 +16,9 @@ def with_env(vars)
         end
       end
 
-      if Open3.respond_to?(:capture3) # 1.9+
-        def shell_out(*command)
-          stdout, stderr, status = Open3.capture3(*command)
```
Comment (pirj) [inline lib/rspec/support/spec/shell_out.rb:21]: I'm not sure how this used to work.
jruby-9.1 (9.1.17.0):
```
> require 'open3'
 => true
jruby-9.1.17.0 :003 > Open3.respond_to?(:capture3)
 => true
jruby-9.1.17.0 :004 > o,e,s=Open3.capture3("ruby -e 'warn \"lol\"'")
lol
 => ["", "", #<Process::Status: pid 12445 exit 0>]
```

jruby-9.2 (9.2.13.0), MRI 2.7.1:
```
> require 'open3'
=> true
[2] pry(main)> o,e,s=Open3.capture3("ruby -e 'warn \"lol\"'")
=> ["", "lol\n", #<Process::Status: pid 12883 exit 0>]
```

Can't find anything related to `capture3` in JRuby's changelog.
I was going to add a check for JRuby < 9.2 and use `popen3`, but:
```
jruby-9.1.17.0 :006 > Open3.popen3("ruby -e 'puts \"lol\"'") do |_,o,e|
jruby-9.1.17.0 :007 >     puts "ERR: #{e.read}", "OUT: #{o.read}"
jruby-9.1.17.0 :008?>   end
lol
ERR:
OUT:
 => nil
```

also, there were two `popen3` related issues fixed in 9.1 and 9.2:
#5235 - popen3 doesn't works fine with java 9/10 and jruby > 1.9.13
#3948 - Open3.popen3 with block fails on Windows
We can't discard Java 9/10 and Windows, can we?

Locally, I'm getting this with 9.1.17.0:
```
  1) rspec warnings and deprecations works when required in isolation
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected "" to start with "DEPRECATION: foo is deprecated"

Failed examples:

rspec ./spec/rspec/support/warnings_spec.rb:11
```
This also fails in [GHA](https://github.com/rspec/rspec-support/runs/1438630956?check_suite_focus=true), and locally on `4-0-dev`, and `main`, with both my changes to other repos and other RSpec gems from RubyGems.

`USE_GIT_REPOS=1` doesn't work with Bunlder 2:
```
NoMethodError: undefined method `[]' for nil:NilClass
  /Users/pirj/.rvm/rubies/jruby-9.1.17.0/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/source/git/git_proxy.rb:90:in `version'
  /Users/pirj/.rvm/rubies/jruby-9.1.17.0/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/source/git/git_proxy.rb:147:in `block in copy_to'
  org/jruby/RubyDir.java:323:in `chdir'
```

Yet, still, with Bundler 1 and `rspec-*` from repos, the failure remains.

So, on `main`, with git repos, on JRuby 9.1.17.0, I'm getting:
```
520 examples, 3 failures, 5 pending

Failed examples:

rspec ./spec/rspec/support/spec/shell_out_spec.rb:6 # RSpec::Support::ShellOut shells out and returns stdout and stderr
rspec ./spec/rspec/support/spec/shell_out_spec.rb:33 # RSpec::Support::ShellOut passes along the provided ruby flags
rspec ./spec/rspec/support/warnings_spec.rb:11 # rspec warnings and deprecations works when required in isolation
```

which are exactly the same failures I'm getting with my changes on CI.

Is this something you've seen along your journey with GHA, @JonRowe, @benoittgt ?

Comment (pirj) [reply lib/rspec/support/spec/shell_out.rb:21]: Just in case:
```
$ ruby --version
jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 14.0.1+14 on 14.0.1+14 +jit [darwin-x86_64]
```

File: lib/rspec/support/ruby_features.rb [hunk 17]
```diff
@@ -103,88 +60,20 @@ def supports_taint?
...
-      if ripper_requirements.all?
-        def ripper_supported?
-          true
-        end
-      else
+      # Ripper on JRuby 9.0.0.0.rc1 - 9.1.8.0 reports wrong line number
+      # or cannot parse source including `:if`.
+      # Ripper on JRuby 9.x.x.x < 9.1.17.0 can't handle keyword arguments
+      # Neither can JRuby prior to 9.2.1.0
+      if Ruby.rbx? || (Ruby.jruby? && JRUBY_VERSION < '9.2.1.0')
```
Comment (pirj) [inline lib/rspec/support/ruby_features.rb:68]: @JonRowe, do we keep Rubinius support, and this check here, and just dropping it from our CI matrix? Or should I remove this check, and only keep JRuby check?

**Comment by pirj** [comment]
No CI-related files included in this change!
Suddenly an unexpectedly all-green 🎉 
@benoittgt @JonRowe welcome for a review.

File: maintenance-branch [hunk 18]
```diff
@@ -1 +1 @@
-4-0-dev
\ No newline at end of file
+drop-old-rubies
```
Comment (pirj) [inline maintenance-branch:1]: ⚠️ This change is temporary and needs to be removed before merging, or soon after ⚠️ 

This is due to changes from sibling PRs being inter-dependent, e.g. a removed `jruby_9000?` method is still in use in `rspec-core` on branch 4-0-dev, but all its usages are removed on branch drop-old-rubies.

File: Changelog.md [hunk 19]
```diff
@@ -1,3 +1,7 @@
+# Development (unreleased)
+
+* Drop support for Ruby < 2.3. (Phil Pirozhkov, #436)
```
Comment (JonRowe) [inline Changelog.md:3]:
```suggestion
## Breaking Changes

* Ruby < 2.3 is no longer supported. (Phil Pirozhkov, #1349)
```

File: Gemfile [hunk 20]
```diff
@@ -13,51 +13,21 @@ branch = File.read(File.expand_path("../maintenance-branch", __FILE__)).chomp
...
 
-if RUBY_VERSION < '2.3.0' && !!(RbConfig::CONFIG['host_os'] =~ /cygwin|mswin|mingw|bccwin|wince|emx/)
-  gem "childprocess", "< 1.0.0"
-elsif RUBY_VERSION < '2.3.0'
-  gem "childprocess", "< 3.0.0"
-else
-  gem "childprocess", ">= 3.0.0"
-end
+gem "childprocess", ">= 3.0.0"
+gem 'ffi', '~> 1.13.0'
```
Comment (JonRowe) [inline Gemfile:23]: This is incorrect, it needs 1.12 until when theres no Rubygems usage?

File: lib/rspec/support.rb [hunk 21]
```diff
@@ -12,22 +12,13 @@ module Support
...
-          require_relative.call("#{lib}/#{f}")
-        end
-      else
-        (class << self; self; end).__send__(:define_method, name) do |f|
-          require "rspec/#{lib}/#{f}"
-        end
+      define_singleton_method("require_rspec_#{lib}") do |f|
+        require_relative.call("#{lib}/#{f}")
       end
     end
```
Comment (JonRowe) [inline lib/rspec/support.rb:18]: :heart:

File: lib/rspec/support/comparable_version.rb [hunk 22]
```diff
@@ -1,46 +0,0 @@
-module RSpec
```
Comment (JonRowe) [inline lib/rspec/support/comparable_version.rb:1]: Restore this please, it's used for better comparison of the 4 digit JRuby strings.

File: lib/rspec/support/method_signature_verifier.rb (hunk 4 above)
[the remark this answers is not in the document]
Comment (JonRowe) [reply lib/rspec/support/method_signature_verifier.rb:192]: Did you double check 9.1.x.x.?

File: lib/rspec/support/mutex.rb [hunk 23]
```diff
@@ -1,73 +1,11 @@
...
-    class Mutex
-      def initialize
-        @waiting = []
-        @locked = false
-        @waiting.taint
-        taint
+    class Mutex < ::Mutex
+      class << self
+        define_method(:new, &::Mutex.method(:new))
       end
```
Comment (JonRowe) [inline lib/rspec/support/mutex.rb:8]: 💜

File: lib/rspec/support/ruby_features.rb [hunk 24]
```diff
@@ -28,22 +27,10 @@ def jruby?
         RUBY_PLATFORM == 'java'
       end
 
-      def jruby_version
-        @jruby_version ||= ComparableVersion.new(JRUBY_VERSION)
-      end
```
Comment (JonRowe) [inline lib/rspec/support/ruby_features.rb:33]: Restore this.

File: lib/rspec/support/ruby_features.rb (hunk 5 above)
[the remark this answers is not in the document]
Comment (JonRowe) [reply lib/rspec/support/ruby_features.rb:46]: Its intended to be available for us to write specs with when needed.

File: lib/rspec/support/ruby_features.rb (hunk 17 above)
Comment (JonRowe) [reply lib/rspec/support/ruby_features.rb:68]: Keep the check, and just drop from our CI matrix. If someone comes to us with Rubinius or Truffle problems we will try to help, just not going to run CI agains them, put back the call to `jruby_version` though :)

File: maintenance-branch (hunk 18 above)
Comment (JonRowe) [reply maintenance-branch:1]: We'll be merging this PR last, so its should be safe to drop this.

File: spec/rspec/support/comparable_version_spec.rb [hunk 25]
```diff
@@ -1,39 +0,0 @@
-require 'rspec/support/comparable_version'
```
Comment (JonRowe) [inline spec/rspec/support/comparable_version_spec.rb:1]: Restore.

File: spec/rspec/support/ruby_features_spec.rb [hunk 26]
```diff
@@ -151,21 +112,17 @@ def ripper_can_parse_source_referencing_keyword_arguments?
...
+                !::Ripper.sexp('def a(**kw_args); end').nil?
+              rescue NoMethodError
+                false
               end
             end
           end
         end
 
         it 'returns whether Ripper is correctly implemented in the current environment' do
-          if RSpec::Support::Ruby.jruby? && RSpec::Support::Ruby.jruby_version < '9.2.1.0'
```
Comment (JonRowe) [inline spec/rspec/support/ruby_features_spec.rb:168]: Restore jruby_version check.

File: lib/rspec/support/reentrant_mutex.rb (hunk 11 above)
Comment (JonRowe) [reply lib/rspec/support/reentrant_mutex.rb:49]: I still feel it would be better to roll the other file in here.

File: lib/rspec/support/spec/stderr_splitter.rb (hunk 12 above)
Comment (JonRowe) [reply lib/rspec/support/spec/stderr_splitter.rb:49]: Still this.

File: lib/rspec/support/spec/shell_out.rb (hunk 16 above)
Comment (JonRowe) [reply lib/rspec/support/spec/shell_out.rb:21]: Er. Pass.

**Review by JonRowe — CHANGES_REQUESTED** [review]
Looking good overall, some comments still to be addressed and some stuff to put back.

File: lib/rspec/support/method_signature_verifier.rb (hunk 4 above)
[the remark this answers is not in the document]
Comment (pirj) [reply lib/rspec/support/method_signature_verifier.rb:192]: I did, but with 9.1.17.0.

WDYT of temporarily adding an earlier version to CI, like e.g. 9.1.7.0 that we had previously?

File: lib/rspec/support/ruby_features.rb (hunk 5 above)
[the remark this answers is not in the document]
Comment (pirj) [reply lib/rspec/support/ruby_features.rb:46]: The most recent usage of it was ~10 years ago.
When writing specs we can use `unless: mri?` in place of `if: non_mri?`, does it do the job?

File: Gemfile (hunk 20 above)
Comment (pirj) [reply Gemfile:23]: Again, I left this intact 😆 

image

Will fix this across repos 👍

File: maintenance-branch (hunk 18 above)
Comment (pirj) [reply maintenance-branch:1]: I can't drop this one - other repos' 4-0-dev branches still use methods that we've removed here (`jruby_version` is one example 😉 ). If we run their corresponding build steps, their specs will fail.

Let's remove this change once we've merged the rest of the repos?

**Comment by pirj** [comment]
Updates:
 - reverted `jruby_version` removal and its usages
 - pinned `ffi` at `~> 1.12.0`
 - accepted Changelog proposed change (breaking change section)
 - reverted error filtering changes in stderr_splitter

File: lib/rspec/support/method_signature_verifier.rb (hunk 4 above)
[the remark this answers is not in the document]
Comment (pirj) [reply lib/rspec/support/method_signature_verifier.rb:192]: `Java::JavaLang::String.instance_method(:char_at).arity` resolves to `1` in all of 9.2.13.0, 9.1.17.0, 9.1.7.0, and even 9.1.0.0.

So it's not like that it's fixed, but more like we don't support versions anymore that had that issue.

**Comment by pirj** [comment]
Update: combined ReentrantMutex with Mutex.

File: lib/rspec/support/recursive_const_methods.rb [hunk 27]
```diff
@@ -5,52 +5,27 @@ module Support
...
-        end
-
-        def constants_defined_on(mod)
-          mod.constants.select { |c| const_defined_on?(mod, c) }
-        end
-      else
-        def const_defined_on?(mod, const_name)
-          mod.const_defined?(const_name, false)
-        end
+      #   C.const_get("Hash") # => ::Hash
```
Comment (JonRowe) [inline lib/rspec/support/recursive_const_methods.rb:12]:
```suggestion
      # Then:
      #   C.const_get("Hash") # => ::Hash
```

File: lib/rspec/support/recursive_const_methods.rb [hunk 28]
```diff
@@ -5,52 +5,27 @@ module Support
     module RecursiveConstMethods
       # We only want to consider constants that are defined directly on a
       # particular module, and not include top-level/inherited constants.
-      # Unfortunately, the constant API changed between 1.8 and 1.9, so
-      # we need to conditionally define methods to ignore the top-level/inherited
-      # constants.
       #
-      # Given:
```
Comment (JonRowe) [inline lib/rspec/support/recursive_const_methods.rb:12]: I think it reads better if this goes back.

Comment (pirj) [reply lib/rspec/support/recursive_const_methods.rb:12]: Agree, it is non-trivial, and additional verbosity won't hurt.

File: maintenance-branch (hunk 18 above)
Comment (JonRowe) [reply maintenance-branch:1]: Other repos are merged, do you want to drop this change?

**Review by JonRowe — CHANGES_REQUESTED** [review]
Almost there, just the branch pinning to drop and see if it builds :joy:

**Comment by pirj** [comment]
Update: reset the temporary `maintenance-branch` commit.

Green! 💚

**Comment by pirj** [comment]
🎉
