### PR TITLE
Prefer calling `expected == actual` over `actual == expected`.

### PR DESCRIPTION
**Pull request by myronmarston**
This ensures that rspec-mocks' `anything` will always match,
even against objects that implement `==` wrongly.

### CODE REVIEW

File: spec/rspec/support/fuzzy_matcher_spec.rb [hunk 1]
```diff
@@ -56,6 +56,37 @@ module Support
...
+            other.r == r && other.g == g && other.b == b
+          end
+        end
+
+        before(:context) do
+          expect { Color.new(0, 0, 0) == Object.new }.to raise_error(NoMethodError, /undefined method `r'/)
+        end
+
+        it 'can match against an expected value that matches anything' do
+          anything = Object.new.tap do |o|
```
Comment (samphippen) [inline spec/rspec/support/fuzzy_matcher_spec.rb]: This could just be `lambda { |*_| true }` right? Do you think that's better?

**Comment by samphippen** [comment]
One comment, otherwise good to merge.

File: spec/rspec/support/fuzzy_matcher_spec.rb (hunk 1 above)
Comment (myronmarston) [inline spec/rspec/support/fuzzy_matcher_spec.rb]: I thought about using that, but `Lambda#===` was new in 1.9 so this doesn't work on 1.8.7.
